//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websiteBALO.Models
{
    using System;
    using System.Collections.Generic;

    public partial class THAMGIA
    {
        public int Mabalo { get; set; }
        public int MaTH { get; set; }
        public string vaitro { get; set; }
        public string vitri { get; set; }

        public virtual SANPHAM SANPHAM { get; set; }
        public virtual THUONGHIEUSP THUONGHIEUSP { get; set; }
    }
}
